import type { Metadata } from "next";
import { Sen } from "next/font/google";
import "../globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import StoreProvider from "./StoreProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import SideNavbar from "@/components/SideNavbar";
import Header from "@/components/SidebarHeader"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const Josef = Sen({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={Josef.className}>
        <StoreProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative flex flex-col">
              <main className="relative flex bg-black-3">
                <SideNavbar />
                <section className="flex min-h-screen flex-1 flex-col  sm:px-14">
                  <div className="mx-auto flex w-full  flex-col">
                    <div className="flex flex-col md:pb-14">
                      <ToastContainer />
                      <Header/>
                      {children}
                    </div>
                  </div>
                </section>
              </main>
            </div>
          </ThemeProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
